# Generated by Django 2.0.6 on 2018-07-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='labe_name',
            new_name='label_name',
        ),
    ]
