# Generated by Django 2.0.6 on 2018-07-02 12:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0002_auto_20180702_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='VideoView',
        ),
    ]
