# Generated by Django 2.0.6 on 2018-07-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20180706_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_urll',
            field=models.CharField(default='', max_length=25),
        ),
    ]
