# Generated by Django 2.0.6 on 2018-07-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_auto_20180706_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_urll',
            new_name='video_url',
        ),
    ]
