# Generated by Django 2.0.6 on 2018-07-06 20:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0007_auto_20180706_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInterests',
            new_name='UserInterest',
        ),
        migrations.RenameModel(
            old_name='UserWeigths',
            new_name='UserWeigth',
        ),
    ]
