# Generated by Django 2.0.6 on 2018-07-10 16:01

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='defaultvideo'),
            preserve_default=False,
        ),
    ]
