# Generated by Django 2.0.6 on 2018-07-10 16:20

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0010_auto_20180710_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Copy vimeo url eg. "https://vimeo.com/184370580"'),
        ),
    ]
