# Generated by Django 2.0.6 on 2018-07-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0011_auto_20180710_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_myvideo',
        ),
    ]
