# Generated by Django 2.1.2 on 2018-10-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0014_auto_20181026_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterest',
            name='label',
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userweigth',
            name='label',
        ),
        migrations.RemoveField(
            model_name='userweigth',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videolabel',
            name='label',
        ),
        migrations.RemoveField(
            model_name='videolabel',
            name='video',
        ),
        migrations.RemoveField(
            model_name='videoview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videoview',
            name='video',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='UserInterest',
        ),
        migrations.DeleteModel(
            name='UserWeigth',
        ),
        migrations.DeleteModel(
            name='VideoLabel',
        ),
        migrations.DeleteModel(
            name='VideoView',
        ),
    ]
