# Generated by Django 2.1.2 on 2018-10-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0017_auto_20181030_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='POIs',
            new_name='POI',
        ),
    ]
