# Generated by Django 2.1.2 on 2018-11-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0018_auto_20181030_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='coordinate',
        ),
        migrations.AddField(
            model_name='video',
            name='poi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.POI'),
        ),
    ]
