# Generated by Django 2.1.2 on 2018-11-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0019_auto_20181109_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_description',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
