# Generated by Django 2.1.2 on 2018-11-09 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0020_auto_20181109_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
