# Generated by Django 2.1.2 on 2018-11-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0021_bundle_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_description',
            field=models.TextField(default=''),
        ),
    ]
