# Generated by Django 2.1.2 on 2018-11-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0022_auto_20181109_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_owner',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_title',
            field=models.TextField(default=''),
        ),
    ]
