# Generated by Django 2.1.2 on 2018-11-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0024_bundle_number_of_final_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchhistory',
            name='is_liked',
            field=models.SmallIntegerField(default=0),
        ),
    ]
