# Generated by Django 2.1.7 on 2019-04-09 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0025_auto_20181121_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trust', models.BooleanField(default=False)),
                ('is_liked', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('proportion', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('trust_list_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trustee', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person2persons', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.Video')),
            ],
        ),
    ]
