# Generated by Django 2.1.7 on 2019-04-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0026_reclistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclistitem',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.Bundle'),
        ),
    ]
