# Generated by Django 2.1.7 on 2019-04-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0027_reclistitem_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.Bundle'),
        ),
    ]
